org: Raman Khurana
orgGuid: d0ca4a0b-b4b4-4821-83f7-d2146a0bc1c4
name: Use-Case-2
projectGuid: e2b6e5b3-cab6-47cc-a753-e655d3ac8ef0
partitionScheme: HOUR
featureType: Integer
importOptions:
  includesHeader: true
fields:
  - name: Auto-Increment
    type: Integer
    classification: ThrowAway
  - name: DeviceID
    type: String
    classification: Key
  - name: Timestamp
    type: String
    classification: Timestamp
  - name: month_TA1305000030
    type: Integer
    classification: Feature
  - name: week_TA1305000030
    type: Integer
    classification: Feature
  - name: day_TA1305000030
    type: Integer
    classification: Feature
  - name: hour_TA1305000030
    type: Integer
    classification: Feature
  - name: month_TA1306000010
    type: Integer
    classification: Feature
  - name: week_TA1306000010
    type: Integer
    classification: Feature
  - name: day_TA1306000010
    type: Integer
    classification: Feature
  - name: hour_TA1306000010
    type: Integer
    classification: Feature
  - name: month_TA1307000120
    type: Integer
    classification: Feature
  - name: week_TA1307000120
    type: Integer
    classification: Feature
  - name: day_TA1307000120
    type: Integer
    classification: Feature
  - name: hour_TA1307000120
    type: Integer
    classification: Feature
  - name: month_TA1307000126
    type: Integer
    classification: Feature
  - name: week_TA1307000126
    type: Integer
    classification: Feature
  - name: day_TA1307000126
    type: Integer
    classification: Feature
  - name: hour_TA1307000126
    type: Integer
    classification: Feature
  - name: output_label
    type: Double
    classification: Label
